GET http://localhost:3005/health

####

GET http://localhost:3005/api/tickers


####

GET http://localhost:3005/api/tickers/BTC-USD


####

GET http://localhost:3005/api/tickers/BTC-USD/history?days=eee


####
# No route check 
GET http://localhost:3005/api/dafsd